routes/web.php
<?php

use App\Http\Controllers\DriverController;
use App\Http\Controllers\InvoiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'App\Http\Controllers\PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'App\Http\Controllers\PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'App\Http\Controllers\PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'App\Http\Controllers\PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'App\Http\Controllers\PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'App\Http\Controllers\PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'App\Http\Controllers\PageController@upgrade']);
});

Route::group(['middleware' => 'auth'], function () {

//    API

    Route::get('driversApi', [DriverController::class, 'indexApi']);

//    Resources
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::resource('drivers', 'App\Http\Controllers\DriverController');
    Route::resource('invoices', 'App\Http\Controllers\InvoiceController');
    Route::resource('clients','App\Http\Controllers\ClientController');

//  Driver

    Route::post('drivers.store','App\Http\Controllers\DriverController@store');

    Route::post('drivers.store','App\Http\Controllers\DriverController@store');

//    APIS

    Route::get("/invoices_api", [InvoiceController::class, "index_api"])->name("invoice.index_api");

//    Invoice Print & Download Route

    Route::get('/invoices/{id}/print', [InvoiceController::class, 'printInvoice'])->name('invoices.print');
    Route::get('/invoices/{id}/download', [InvoiceController::class, 'downloadInvoice'])->name('invoices.download');

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
	 Route::get('map', function () {return view('pages.maps');})->name('map');
	 Route::get('icons', function () {return view('pages.icons');})->name('icons');
	 Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
        'client_name',
        'client_address',
        'client_contact',
        'client_email',
        'client_website',
        'user_id',
    ];

    public function invoices(){
        return $this->hasMany(Invoice::class);
    }

    public function clientHolder(){
        return $this->belongsTo(User::class);
    }




}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('clients.manage-client');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.new-client');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            "client_name" => 'required|string',
            "client_address" => 'required|string',
            "client_email" => 'required|email',
            "client_contact" => 'required|numeric',
            "representative_name" => 'required|string',
            "representative_contact" => 'required|numeric',
            "client_other_info" => 'required|string',
        ]);
        $user = Auth::user();

        $client = $user->clients()->create([
            'client_name'=>$data['client_name'],
            'client_address'=>$data['client_address'],
            'client_email'=>$data['client_email'],
            'client_contact'=>$data['client_contact'],
            'representative_name'=>$data['representative_name'],
            'representative_contact'=>$data['representative_contact'],
            'client_other_info'=>$data['client_other_info'],
        ]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/clients/manage-client.blade.php
@extends('layouts.app', ['page' => __('Manage Invoice'), 'pageSlug' => 'client-manager'])
@section('content')
<h1>clhoijkd</h1>
@endsection

resources/views/clients/new-client.blade.php
@extends('layouts.app', ['page' => __('Manage Invoice'), 'pageSlug' => 'client-create'])
@section('content')
    <div class="container mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow bg-secondary">
                    <div class="card-header bg-white">
                        <h5 class="title">{{ __('ADD New Client') }}</h5>
                    </div>

                    <form method="post" action="{{ route('clients.store') }}" autocomplete="off">
                        <div class="card-body">
                            @csrf
                            @include('alerts.success')
                            <div class="row">
                                <div class="col-6 form-group{{ $errors->has('client_name') ? ' has-danger' : '' }}">
                                    <label>{{ __('Name') }}</label>
                                    <input type="text" name="client_name"
                                           class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Name') }}" value="{{old('client_name')}}">
                                    @include('alerts.feedback', ['field' => 'client_name'])
                                </div>

                                <div class="col-6 form-group{{ $errors->has('client_contact') ? ' has-danger' : '' }}">
                                    <label>{{ __('Contact') }}</label>
                                    <input type="text" name="client_contact"
                                           class="form-control form-control-alternative {{ $errors->has('client_contact') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Add Contact Number') }}" value="{{ old('client_contact')}}">
                                    @include('alerts.feedback', ['field' => 'client_contact'])
                                </div>

                                <div class="col-12 form-group{{ $errors->has('client_address') ? ' has-danger' : '' }}">
                                    <label>{{ __('Address') }}</label>
                                    <input type="text" name="client_address"
                                           class="form-control form-control-alternative{{ $errors->has('client_address') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('Address') }}" value="{{old('client_address')}}">
                                    @include('alerts.feedback', ['field' => 'client_address'])
                                </div>

                                <div class="col-8 form-group{{ $errors->has('client_email') ? ' has-danger' : '' }}">
                                    <label>{{ __('E-mail') }}</label>
                                    <input type="email" name="client_email"
                                           class="form-control form-control-alternative {{ $errors->has('client_email') ? ' is-invalid' : '' }}"
                                           placeholder="{{ __('E-mail') }}" value="{{old('client_email')}}">
                                    @include('alerts.feedback', ['field' => 'client_email'])
                                </div>
                            </div>
                                <div class="row">
                                    <div class="col-6 form-group{{ $errors->has('representative_name') ? ' has-danger' : '' }}">
                                        <label>{{ __('Representative Name') }}</label>
                                        <input type="text" name="representative_name"
                                               class="form-control form-control-alternative {{ $errors->has('representative_name') ? ' is-invalid' : '' }}"
                                               placeholder="{{ __('Add Representative Name') }}" value="{{ old('representative_name')}}">
                                        @include('alerts.feedback', ['field' => 'contact'])
                                    </div>
                                    <div class="col-6 form-group{{ $errors->has('representative_contact') ? ' has-danger' : '' }}">
                                        <label>{{ __('Representative Contact') }}</label>
                                        <input type="text" name="representative_contact"
                                               class="form-control form-control-alternative {{ $errors->has('representative_contact') ? ' is-invalid' : '' }}"
                                               placeholder="{{ __('Add Representative Contact') }}" value="{{ old('representative_contact')}}">
                                        @include('alerts.feedback', ['field' => 'representative_contact'])
                                    </div>
                                    <div class="col-12 form-group{{ $errors->has('client_other_info') ? ' has-danger' : '' }}">
                                        <label>{{ __('Client Other Info') }}</label>
                                        <input type="text" name="client_other_info"
                                               class="form-control form-control-alternative {{ $errors->has('client_other_info') ? ' is-invalid' : '' }}"
                                               placeholder="{{ __('Add Client Other Info') }}" value="{{ old('client_other_info')}}">
                                        @include('alerts.feedback', ['field' => 'client_other_info'])
                                    </div>
                                </div>

                        </div>
                        <div class="text-center m-4">
                            <button type="submit" class="btn btn-fill btn-primary">{{ __('Save') }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection